# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'omnicomm_gui.ui'
#
# Created: Sun Jun 10 15:33:21 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(420, 600)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "OmniComm", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.format_table = QtGui.QTabWidget(self.centralwidget)
        self.format_table.setObjectName(_fromUtf8("format_table"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget = QtGui.QTabWidget(self.tab)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 191, 172))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.tab_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "COM Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Baud:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Timeout:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.serial_timeout_edit = QtGui.QLineEdit(self.tab_2)
        self.serial_timeout_edit.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.serial_timeout_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.serial_timeout_edit.setObjectName(_fromUtf8("serial_timeout_edit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.serial_timeout_edit)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Buffer Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.serial_buffsize_edit = QtGui.QLineEdit(self.tab_2)
        self.serial_buffsize_edit.setText(QtGui.QApplication.translate("MainWindow", "1024", None, QtGui.QApplication.UnicodeUTF8))
        self.serial_buffsize_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.serial_buffsize_edit.setObjectName(_fromUtf8("serial_buffsize_edit"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.serial_buffsize_edit)
        self.serial_connect_btn = QtGui.QPushButton(self.tab_2)
        self.serial_connect_btn.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.serial_connect_btn.setObjectName(_fromUtf8("serial_connect_btn"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.serial_connect_btn)
        self.serial_disconnect_btn = QtGui.QPushButton(self.tab_2)
        self.serial_disconnect_btn.setText(QtGui.QApplication.translate("MainWindow", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.serial_disconnect_btn.setObjectName(_fromUtf8("serial_disconnect_btn"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.serial_disconnect_btn)
        self.serial_baud_edit = QtGui.QLineEdit(self.tab_2)
        self.serial_baud_edit.setText(QtGui.QApplication.translate("MainWindow", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.serial_baud_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.serial_baud_edit.setObjectName(_fromUtf8("serial_baud_edit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.serial_baud_edit)
        self.serial_port_edit = QtGui.QLineEdit(self.tab_2)
        self.serial_port_edit.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.serial_port_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.serial_port_edit.setObjectName(_fromUtf8("serial_port_edit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.serial_port_edit)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.tab_3)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Port #:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Bind Addres:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Timeout:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.udp_timeout_edit = QtGui.QLineEdit(self.tab_3)
        self.udp_timeout_edit.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.udp_timeout_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.udp_timeout_edit.setObjectName(_fromUtf8("udp_timeout_edit"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.udp_timeout_edit)
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Buffer Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_10)
        self.udp_buffsize_edit = QtGui.QLineEdit(self.tab_3)
        self.udp_buffsize_edit.setText(QtGui.QApplication.translate("MainWindow", "1024", None, QtGui.QApplication.UnicodeUTF8))
        self.udp_buffsize_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.udp_buffsize_edit.setObjectName(_fromUtf8("udp_buffsize_edit"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.udp_buffsize_edit)
        self.udp_connect_btn = QtGui.QPushButton(self.tab_3)
        self.udp_connect_btn.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.udp_connect_btn.setObjectName(_fromUtf8("udp_connect_btn"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.udp_connect_btn)
        self.udp_disconnect_btn = QtGui.QPushButton(self.tab_3)
        self.udp_disconnect_btn.setText(QtGui.QApplication.translate("MainWindow", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.udp_disconnect_btn.setObjectName(_fromUtf8("udp_disconnect_btn"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.udp_disconnect_btn)
        self.udp_port_edit = QtGui.QLineEdit(self.tab_3)
        self.udp_port_edit.setText(QtGui.QApplication.translate("MainWindow", "1350", None, QtGui.QApplication.UnicodeUTF8))
        self.udp_port_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.udp_port_edit.setObjectName(_fromUtf8("udp_port_edit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.udp_port_edit)
        self.udp_bindaddr_edit = QtGui.QLineEdit(self.tab_3)
        self.udp_bindaddr_edit.setText(QtGui.QApplication.translate("MainWindow", "0.0.0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.udp_bindaddr_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.udp_bindaddr_edit.setObjectName(_fromUtf8("udp_bindaddr_edit"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.udp_bindaddr_edit)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(0, 200, 381, 301))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Data View", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "View as:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout.addWidget(self.label_12)
        self.data_view_encoding_combo = QtGui.QComboBox(self.groupBox)
        self.data_view_encoding_combo.setObjectName(_fromUtf8("data_view_encoding_combo"))
        self.data_view_encoding_combo.addItem(_fromUtf8(""))
        self.data_view_encoding_combo.setItemText(0, QtGui.QApplication.translate("MainWindow", "ASCII", None, QtGui.QApplication.UnicodeUTF8))
        self.data_view_encoding_combo.addItem(_fromUtf8(""))
        self.data_view_encoding_combo.setItemText(1, QtGui.QApplication.translate("MainWindow", "Hex", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout.addWidget(self.data_view_encoding_combo)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.raw_data_textEdit = QtGui.QPlainTextEdit(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        self.raw_data_textEdit.setFont(font)
        self.raw_data_textEdit.setAutoFillBackground(False)
        self.raw_data_textEdit.setReadOnly(True)
        self.raw_data_textEdit.setBackgroundVisible(False)
        self.raw_data_textEdit.setObjectName(_fromUtf8("raw_data_textEdit"))
        self.verticalLayout_2.addWidget(self.raw_data_textEdit)
        self.format_table.addTab(self.tab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.tab_5)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Format String:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.format_lineEdit = QtGui.QLineEdit(self.tab_5)
        self.format_lineEdit.setText(QtGui.QApplication.translate("MainWindow", "<BlBffffffffff", None, QtGui.QApplication.UnicodeUTF8))
        self.format_lineEdit.setObjectName(_fromUtf8("format_lineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.format_lineEdit)
        self.label_2 = QtGui.QLabel(self.tab_5)
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "TextLabel:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.labels_lineEdit = QtGui.QLineEdit(self.tab_5)
        self.labels_lineEdit.setText(QtGui.QApplication.translate("MainWindow", "id,seqack,mode,thrust_sfn,hinge_x,hinge_y,rcs0,rcs1,rcs2,rcs3,mass_est,mass_fuel,mass_lox", None, QtGui.QApplication.UnicodeUTF8))
        self.labels_lineEdit.setObjectName(_fromUtf8("labels_lineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.labels_lineEdit)
        self.label_3 = QtGui.QLabel(self.tab_5)
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Units:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.units_lineEdit = QtGui.QLineEdit(self.tab_5)
        self.units_lineEdit.setText(QtGui.QApplication.translate("MainWindow", "unknown,unknown,unknown,N,deg,deg,uknown,uknown,uknown,uknown,kg,kg,kg", None, QtGui.QApplication.UnicodeUTF8))
        self.units_lineEdit.setObjectName(_fromUtf8("units_lineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.units_lineEdit)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.update_format_btn = QtGui.QPushButton(self.tab_5)
        self.update_format_btn.setText(QtGui.QApplication.translate("MainWindow", "Update Packet Format", None, QtGui.QApplication.UnicodeUTF8))
        self.update_format_btn.setObjectName(_fromUtf8("update_format_btn"))
        self.verticalLayout_3.addWidget(self.update_format_btn)
        self.tm_table = QtGui.QTableWidget(self.tab_5)
        self.tm_table.setAlternatingRowColors(False)
        self.tm_table.setShowGrid(False)
        self.tm_table.setGridStyle(QtCore.Qt.DashLine)
        self.tm_table.setRowCount(1)
        self.tm_table.setColumnCount(5)
        self.tm_table.setObjectName(_fromUtf8("tm_table"))
        self.tm_table.horizontalHeader().setCascadingSectionResizes(False)
        self.tm_table.horizontalHeader().setDefaultSectionSize(75)
        self.tm_table.horizontalHeader().setStretchLastSection(False)
        self.tm_table.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tm_table)
        self.format_table.addTab(self.tab_5, _fromUtf8(""))
        self.verticalLayout.addWidget(self.format_table)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuConnect = QtGui.QMenu(self.menubar)
        self.menuConnect.setTitle(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConnect.setObjectName(_fromUtf8("menuConnect"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Packet_Definition = QtGui.QAction(MainWindow)
        self.actionLoad_Packet_Definition.setText(QtGui.QApplication.translate("MainWindow", "Load Packet Definition", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Packet_Definition.setObjectName(_fromUtf8("actionLoad_Packet_Definition"))
        self.actionSave_Packet_Definition = QtGui.QAction(MainWindow)
        self.actionSave_Packet_Definition.setText(QtGui.QApplication.translate("MainWindow", "Save Packet Definition", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Packet_Definition.setObjectName(_fromUtf8("actionSave_Packet_Definition"))
        self.actionSerial_COM = QtGui.QAction(MainWindow)
        self.actionSerial_COM.setText(QtGui.QApplication.translate("MainWindow", "Serial COM", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSerial_COM.setObjectName(_fromUtf8("actionSerial_COM"))
        self.actionUDP_Socket = QtGui.QAction(MainWindow)
        self.actionUDP_Socket.setText(QtGui.QApplication.translate("MainWindow", "UDP Socket", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUDP_Socket.setObjectName(_fromUtf8("actionUDP_Socket"))
        self.actionFile = QtGui.QAction(MainWindow)
        self.actionFile.setText(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFile.setObjectName(_fromUtf8("actionFile"))
        self.menuFile.addAction(self.actionLoad_Packet_Definition)
        self.menuFile.addAction(self.actionSave_Packet_Definition)
        self.menuConnect.addAction(self.actionSerial_COM)
        self.menuConnect.addAction(self.actionUDP_Socket)
        self.menuConnect.addAction(self.actionFile)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuConnect.menuAction())

        self.retranslateUi(MainWindow)
        self.format_table.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Serial (COM)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "UDP", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.format_table.setTabText(self.format_table.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.tm_table.setSortingEnabled(True)
        self.format_table.setTabText(self.format_table.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "TM", None, QtGui.QApplication.UnicodeUTF8))

